[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "scripts"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@/=lib/forge-std/src/"
]

fs_permissions = [
    { access = "read-write", path = "var/"},
]
ffi = true

solc_version = "0.8.16"
optimizer = true
via_ir=true
optimizer_runs = 999_999
bytecode_hash = "none"
evm_version = "london"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
